### ISSUE TITLE
Clarify available LESS configuration options

### ISSUE THREAD

**Issue by harriha** [plus3network/gulp-less#167]
Hi,

The paragraph about the available LESS configuration options (https://github.com/plus3network/gulp-less#options) is imo a bit misleading on a first glance:
- The link should/could be pointing to http://lesscss.org/usage/index.html#command-line-usage-options instead, all those options seem to be available.
- Even though the link to full options is there, listing only two config options gives easily the impression that those are the only things you can do. Maybe the wording could be changed a bit to make it clearer that the mentioned ones are just examples, and there's much more options available?

**Comment by piotr-cz** [comment]
+1

**Comment by dacostafilipe** [comment]
Instead of having a link to the CLI options, you should put a link to the browser usage options (http://lesscss.org/usage/index.html#using-less-in-the-browser-options) because those are the names we need to use (ex: **modifyVars** and not **modify-var**)

I've tested both **modifyVars** and **globalVars** and can confirm that it works.
